### ISSUE TITLE
rayn fails to compile with fabric 7.4.0

### ISSUE THREAD

**Issue by jnweiger** [LUPLUV/rayn#2]
Seen on Ubuntu 25.4 with a fresh git pull today:

npm tells me, several of my dependencies have security issues.

To fix the security issues, I am using: $ npm audit fix --force
...
fabric  <=7.1.0
Severity: high
Fabric.js Affected by Stored XSS via SVG Export - https://github.com/advisories/GHSA-hfvx-25r5-qc3w
Depends on vulnerable versions of canvas
fix available via `npm audit fix --force`
Will install fabric@7.4.0, which is a breaking change
node_modules/fabric

Now rayn frontend fails to compile:

$ wails dev -tags webkit2_41
Wails CLI v2.12.0

Executing: go mod tidy
  • Generating bindings: Done.
  • Installing frontend dependencies: Done.
  • Compiling frontend:     
    > frontend@0.0.0 build
    > tsc && vite build
    
    src/components/Workspace.tsx(2,10): error TS2305: Module '"fabric"' has no exported member 'fabric'.
    src/components/Workspace.tsx(300,48): error TS7006: Parameter 'objects' implicitly has an 'any' type.
    src/components/Workspace.tsx(300,57): error TS7006: Parameter 'options' implicitly has an 'any' type.
    src/components/Workspace.tsx(308,28): error TS7006: Parameter 'obj' implicitly has an 'any' type.
    
  ERROR   exit status 2

The updated packages are:
```
diff --git a/frontend/package-lock.json b/frontend/package-lock.json
index 84aca8c..73b9621 100644
--- a/frontend/package-lock.json
+++ b/frontend/package-lock.json
@@ -12,7 +12,7 @@
-        "fabric": "^5.3.0",
+        "fabric": "^7.4.0",
-        "@vitejs/plugin-react": "^2.0.1",
+        "@vitejs/plugin-react": "^6.0.2",
-        "vite": "^3.0.7"
+        "vite": "^8.0.14"

...
```

**Comment by jnweiger** [comment]
Tried as a workaround: 
```
npm uninstall fabric
npm install fabric@5.3.0
```
This does not help. the compile error persists. I am stuck in npm dependency hell now.

**Comment by jnweiger** [comment]
fixed in latest code. Thanks!
